[package]
name = "aivdm-cli"
description = "Command-line demo/decoder for aivdm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "aivdm"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
aivdm = { path = "../aivdm" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
