#ifndef AIVDM_H
#define AIVDM_H

/* Generated by cbindgen from crates/aivdm-ffi/src/lib.rs. Do not edit by hand: run `cbindgen --config crates/aivdm-ffi/cbindgen.toml --crate aivdm-ffi --output crates/aivdm-ffi/include/aivdm.h` and commit the result. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by [`aivdm_decode_line`].
 */
enum AivdmError
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  /**
   * No error.
   */
  AIVDM_ERROR_OK = 0,
  /**
   * The `line` pointer was NULL.
   */
  AIVDM_ERROR_NULL_INPUT = 1,
  /**
   * `line` was not valid UTF-8.
   */
  AIVDM_ERROR_INVALID_UTF8 = 2,
  /**
   * The NMEA sentence itself was malformed (bad checksum, wrong field
   * count, unsupported talker/formatter, invalid armor character).
   */
  AIVDM_ERROR_NMEA = 3,
  /**
   * The sentence is one fragment of a multi-part message; this
   * decode-only entry point only handles single-fragment sentences.
   */
  AIVDM_ERROR_INCOMPLETE_FRAGMENT = 4,
  /**
   * A fragment-reassembly error (not produced by this entry point, which
   * does no reassembly, but reserved for API symmetry).
   */
  AIVDM_ERROR_FRAGMENT = 5,
  /**
   * The payload was truncated or otherwise malformed at the bit level.
   */
  AIVDM_ERROR_BIT = 6,
  /**
   * The message type is unknown, or a field held an invalid value.
   */
  AIVDM_ERROR_MESSAGE = 7,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AivdmError AivdmError;
#else
typedef uint8_t AivdmError;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Opaque handle to a decoded AIS message, owned by the caller until freed
 * with [`aivdm_message_free`].
 */
typedef struct AivdmMessage AivdmMessage;

/**
 * Decodes a single, complete, single-fragment `!AIVDM`/`!AIVDO` line.
 *
 * On success, returns a non-NULL handle (free it with
 * [`aivdm_message_free`] when done) and, if `out_error` is non-NULL, writes
 * [`AivdmError::Ok`] through it. On failure, returns NULL and, if
 * `out_error` is non-NULL, writes the reason through it.
 *
 * # Safety
 * `line` must be NULL or a pointer to a NUL-terminated C string valid for
 * reads for the duration of this call. `out_error` must be NULL or a
 * pointer valid for a single `u8`-sized write.
 */
struct AivdmMessage *aivdm_decode_line(const char *line, AivdmError *out_error);

/**
 * Frees a message handle returned by [`aivdm_decode_line`]. Passing NULL is
 * a no-op.
 *
 * # Safety
 * `msg` must be NULL or a pointer previously returned by
 * [`aivdm_decode_line`] that has not already been freed.
 */
void aivdm_message_free(struct AivdmMessage *msg);

/**
 * The ITU-R M.1371 message type number (1-27) of a decoded message.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from [`aivdm_decode_line`].
 */
uint8_t aivdm_message_type(const struct AivdmMessage *msg);

/**
 * How many times a repeater has relayed this message (0-3).
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from [`aivdm_decode_line`].
 */
uint8_t aivdm_message_repeat_indicator(const struct AivdmMessage *msg);

/**
 * The source station MMSI.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from [`aivdm_decode_line`].
 */
uint32_t aivdm_message_mmsi(const struct AivdmMessage *msg);

/**
 * Reads the position, in decimal degrees, off a message.
 *
 * Returns `true` and writes `*out_lat`/`*out_lon` if this message type
 * carries a position and it is marked available; returns `false` (leaving
 * the outputs untouched) otherwise.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from
 * [`aivdm_decode_line`]. `out_lat` and `out_lon` must be valid pointers to
 * writable `f64`s.
 */
bool aivdm_message_position(const struct AivdmMessage *msg, double *out_lat, double *out_lon);

/**
 * Reads speed over ground, in knots, off a message.
 *
 * Returns `true` and writes `*out_sog` if this message type carries a
 * speed and it is marked available; returns `false` otherwise.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from
 * [`aivdm_decode_line`]. `out_sog` must be a valid pointer to a writable `f64`.
 */
bool aivdm_message_sog_knots(const struct AivdmMessage *msg, double *out_sog);

/**
 * Reads course over ground, in degrees, off a message.
 *
 * Returns `true` and writes `*out_cog` if this message type carries a
 * course and it is marked available; returns `false` otherwise.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from
 * [`aivdm_decode_line`]. `out_cog` must be a valid pointer to a writable `f64`.
 */
bool aivdm_message_cog_degrees(const struct AivdmMessage *msg, double *out_cog);

/**
 * Reads true heading, in whole degrees (0-359), off a message.
 *
 * Returns `true` and writes `*out_heading` if this message type carries a
 * heading and it is marked available; returns `false` otherwise.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from
 * [`aivdm_decode_line`]. `out_heading` must be a valid pointer to a writable `u16`.
 */
bool aivdm_message_heading_degrees(const struct AivdmMessage *msg, uint16_t *out_heading);

/**
 * Reads the raw navigational status code (0-15, ITU-R M.1371 Table 45) off
 * a message.
 *
 * Returns `true` and writes `*out_status` if this message type carries a
 * navigational status; returns `false` otherwise.
 *
 * # Safety
 * `msg` must be NULL or a valid, non-freed handle from
 * [`aivdm_decode_line`]. `out_status` must be a valid pointer to a writable `u8`.
 */
bool aivdm_message_navigation_status(const struct AivdmMessage *msg, uint8_t *out_status);

/**
 * The `aivdm` crate version, as a NUL-terminated, statically allocated
 * string (e.g. `"0.1.0"`). Do not free.
 */
const char *aivdm_version(void);

#endif  /* AIVDM_H */
